### ISSUE TITLE
add_log_key_value参数k_len、v_len传反了

### ISSUE THREAD

**Issue by tedli** [aliyun/aliyun-log-c-sdk#1]
`void add_log_key_value(log_group_builder* bder,char* k,size_t v_len,char* v,size_t k_len)`
`log_builder.c` 85 行
`k`用的是`v_len`
`v`用的是`k_len`
另外用`CMakeList.txt`做build有问题，build不通。
还有日志服务说有Go的API，没找到，现在用cgo调的C API，希望提供Go的。

**Comment by wangjwchn** [comment]
@tedli 
已经更正，
谢谢您的反馈。

**Comment by tedli** [comment]
`log_builder.h`68行extern void add_log_key_value(log_group_builder* bder,char* v,size_t v_len,char* k,size_t k_len);
`log_builder.c`84行`void add_log_key_value(log_group_builder* bder,char* k,size_t v_len,char* v,size_t k_len)`
