### ISSUE TITLE
如果是ECOS系统，有解决方案么？

### ISSUE THREAD

**Issue by bearcubs** [aliyun/aliyun-log-c-sdk#15]
我们的项目希望用到日志服务，可是嵌入式设备资源紧张，系统是ECOS，有解决方案么？

**Comment by shabicheng** [comment]
有的，我们之前集成过RTOS，只需要4-8KB内存，参考bricks分支，需要自己实现底层的网络发送，里面有一个示例。有问题加钉钉 15851856153 
 https://github.com/aliyun/aliyun-log-c-sdk/tree/bricks
