### ISSUE TITLE
lite版本编译安装时还有Json.h安装

### ISSUE THREAD

**Issue by slinkingos** [aliyun/aliyun-log-c-sdk#17]
1、编译好后，make install 出现以下错误。

main@ubuntu:~/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk$ make install
[ 50%] Built target log_c_sdk
[100%] Built target log_c_sdk_static
Install the project...
-- Install configuration: ""
-- Installing: /home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/Release/lib/liblog_c_sdk.so.2.0.0
-- Up-to-date: /home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/Release/lib/liblog_c_sdk.so
-- Installing: /home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/Release/lib/liblog_c_sdk_static.a
CMake Error at cmake_install.cmake:69 (FILE):
  file INSTALL cannot find
  "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/cJSON.h".

make: *** [install] Error 1

2、cmake_install.cmake做了以下修改才可以编译安装：
  FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/log_c_sdk" TYPE FILE FILES
    #    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/cJSON.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/lz4.h"
    #"/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/aos_log.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_define.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_util.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_api.h"
    #    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_http_cont.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_builder.h"
    #"/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/protobuf-c.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_logs.pb-c.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_producer_client.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_producer_common.h"
    "/home/main/workspace/Tbox/TBOX_EC20/ql-ol-sdk/ecpark-app/extlib/aliyun-log-c-sdk/src/log_producer_config.h"
    )

3、想知道这样修改是否有问题？

**Comment by shabicheng** [comment]
您好，make install 确实存在问题，这块我们会进行修复

**Comment by shabicheng** [comment]
问题已经修复
