### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by ykcmi** [aliyun/aliyun-log-c-sdk#19]
我在mac上编译，cmake可以执行成功，
make时，会出现这样的错误，可以帮忙分析是什么原因吗，不能在mac上编译吗
Scanning dependencies of target log_c_sdk
[  2%] Building C object CMakeFiles/log_c_sdk.dir/src/hmac-sha.o
[  4%] Building C object CMakeFiles/log_c_sdk.dir/src/inner_log.o
[  7%] Building C object CMakeFiles/log_c_sdk.dir/src/log_api.o
[  9%] Building C object CMakeFiles/log_c_sdk.dir/src/log_builder.o
[ 12%] Building C object CMakeFiles/log_c_sdk.dir/src/log_producer_client.o
[ 14%] Building C object CMakeFiles/log_c_sdk.dir/src/log_producer_common.o
[ 17%] Building C object CMakeFiles/log_c_sdk.dir/src/log_producer_config.o
[ 19%] Building C object CMakeFiles/log_c_sdk.dir/src/log_producer_manager.o
[ 21%] Building C object CMakeFiles/log_c_sdk.dir/src/log_producer_sender.o
[ 24%] Building C object CMakeFiles/log_c_sdk.dir/src/log_queue.o
[ 26%] Building C object CMakeFiles/log_c_sdk.dir/src/log_util.o
[ 29%] Building C object CMakeFiles/log_c_sdk.dir/src/lz4.o
[ 31%] Building C object CMakeFiles/log_c_sdk.dir/src/md5.o
[ 34%] Building C object CMakeFiles/log_c_sdk.dir/src/sds.o
[ 36%] Building C object CMakeFiles/log_c_sdk.dir/src/sha1.o
[ 39%] Linking C shared library build/Release/lib/liblog_c_sdk.dylib
Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      _post_logs_from_lz4buf in log_api.o
  "_curl_easy_getinfo", referenced from:
      _post_logs_from_lz4buf in log_api.o
  "_curl_easy_init", referenced from:
      _post_logs_from_lz4buf in log_api.o
  "_curl_easy_perform", referenced from:
      _post_logs_from_lz4buf in log_api.o
  "_curl_easy_setopt", referenced from:
      _post_logs_from_lz4buf in log_api.o
  "_curl_easy_strerror", referenced from:
      _sls_log_init in log_api.o
      _post_logs_from_lz4buf in log_api.o
  "_curl_global_cleanup", referenced from:
      _sls_log_destroy in log_api.o
  "_curl_global_init", referenced from:
      _sls_log_init in log_api.o
  "_curl_slist_append", referenced from:
      _post_logs_from_lz4buf in log_api.o
  "_curl_slist_free_all", referenced from:
      _post_logs_from_lz4buf in log_api.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [build/Release/lib/liblog_c_sdk.2.0.0.dylib] Error 1
make[1]: *** [CMakeFiles/log_c_sdk.dir/all] Error 2
make: *** [all] Error 2

**Comment by shabicheng** [comment]
看起来像是没有找到libcurl的lib，头文件可以获取到，但在链接的时候没有libcurl.a就报错了，你可以找一下libcurl的lib所在目录（我这边mac所在路径是 /usr/local/lib/libcurl.a ），然后手动指定 -DCURL_LIBRARY 试试（用法可以搜索一下README）

**Comment by shabicheng** [comment]
fixed
