### ISSUE TITLE
CRYPTO_LIBRARY nofound on raspberry pi

### ISSUE THREAD

**Issue by jokes4u** [aliyun/aliyun-log-c-sdk#20]
cmake 的时候报错
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CRYPTO_LIBRARY
    linked by target "log_producer_sample" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample
    linked by target "log_post_logs_sample" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_benchmark" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample
    linked by target "video_frame_producer_sample" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample
SSL_LIBRARY
    linked by target "log_producer_sample" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample
    linked by target "log_post_logs_sample" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample
    linked by target "log_producer_benchmark" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample
    linked by target "video_frame_producer_sample" in directory /home/pi/lite/aliyun-log-c-sdk-lite/sample

-- Configuring incomplete, errors occurred!

有大佬知道如何处理吗？

**Comment by shabicheng** [comment]
这是编译sample的时候出错，因为没有找到sample目录下CMakeList.txt中的find_library(SSL_LIBRARY ssl) find_library(CRYPTO_LIBRARY crypto) 这两个参数没有找到，如果你编译CURL的时候没有使用SSL，把这两个去掉试试。如果还不行，需要编译一下SSL
