### ISSUE TITLE
sender线程池销毁最大等待时间---配置不生效

### ISSUE THREAD

**Issue by 666charles** [aliyun/aliyun-log-c-sdk#21]
README.md
### 详细配置
| destroy_flusher_wait_sec | flusher线程销毁最大等待时间 | 整数，单位秒，默认为1 |
| destroy_sender_wait_sec | sender线程池销毁最大等待时间 | 整数，单位秒，默认为1 |

#############################
destroy_log_producer_manager函数使用了destroyFlusherWaitTimeoutSec
destroy_log_producer_sender函数也使用了destroyFlusherWaitTimeoutSec，
                                                  本意是使用destroySenderWaitTimeoutSec 吧？

void destroy_log_producer_sender(log_producer_sender * producer_sender, log_producer_config * producer_config)
{
    if (producer_sender->thread_pool == NULL)
    {
        return;
    }
    // add a thread to flush all data out
    apr_thread_pool_thread_max_set(producer_sender->thread_pool, producer_config->sendThreadCount + 1);
    int32_t flush_count = producer_config->destroyFlusherWaitTimeoutSec > 0 ? producer_config->destroyFlusherWaitTimeoutSec * 100 : MAX_SENDER_FLUSH_COUNT;
    int waitCount = 0;

    ...........
}

**Comment by shabicheng** [comment]
感谢建议，您可以提交一个Pull Request哈

**Comment by shabicheng** [comment]
#22  fixed
