### ISSUE TITLE
请问能增加对automake的支持么？

### ISSUE THREAD

**Issue by zhaowq32** [aliyun/aliyun-log-c-sdk#23]
我通过后台脚本编译代码来生成给android用的静态库，我搜索了下cmake的跨平台，大多数都是依赖于ide和gradle的，如何直接使用ndk来完成编译呢？

**Comment by shabicheng** [comment]
好问题，参考： https://github.com/aliyun/aliyun-log-c-sdk/tree/live/projects/android/jni

**Comment by zhaowq32** [comment]
谢谢
