### ISSUE TITLE
推荐使用master分支还是使用releaese里的代码？

### ISSUE THREAD

**Issue by zhaowq32** [aliyun/aliyun-log-c-sdk#24]
你好：
    有2个问题想问下：
1、推荐使用master分支还是使用releaese里的代码？
2、android Android.mk的编译方式没有将对应架构的curl的目录传给编译器，会默认使用系统x86架构的头文件么？会有啥影响么？

**Comment by shabicheng** [comment]
1. 如果是Android，建议使用live分支，其他情况使用lite分支，master分支一般用于服务器
2. mk文件你可以自己改一下，include路径引用自己的编译的curl就行，不要用默认的X86

**Comment by zhaowq32** [comment]
有开关控制么？我的应用开始是需要将消息缓存的，待开关开启后才会真正的进行生产。另外这个线程安全么？

**Comment by shabicheng** [comment]
1. 自动缓存这个事情，producer已经帮你做好了，后台会根据缓存的时间间隔、数据量自动去做，数据都是批量压缩发送的。
2. 是线程安全的

**Comment by zhaowq32** [comment]
我可能描述的不是很清楚，我的目的是想控制日志是否发送往服务器。但这个开关是在应用运行过程中才能获得。所以就需要在获得开关之前，将日志进行缓存，但不发送。当开关变为true时，才进行发送，否则就关闭日志发送功能。

**Comment by shabicheng** [comment]
这个功能我们没有，你可以自己定制，在发送那边加一个标志位，自己控制一下就好了

**Comment by zhaowq32** [comment]
好的  麻烦了
