### ISSUE TITLE
C Producer Lite中依赖的libcurl需要哪些功能支持？

### ISSUE THREAD

**Issue by vintonliu** [aliyun/aliyun-log-c-sdk#31]
C Producer Lite中依赖的libcurl需要哪些功能支持， ./configure 要最小支持哪些功能选项？

**Comment by shabicheng** [comment]
支持HTTP相关的功能即可，如果要用HTTPS，还需要把ssl相关的依赖加上去

**Comment by vintonliu** [comment]
> 支持HTTP相关的功能即可，如果要用HTTPS，还需要把ssl相关的依赖加上去

可以提供下 ./configure的配置吗，谢谢！

**Comment by vintonliu** [comment]
@shabicheng libcurl需要支持zlib吗？

**Comment by shabicheng** [comment]
@vintonliu 可以不用zlib，另外我们这边用的是默认的 ./configure编译的

**Comment by vintonliu** [comment]
@shabicheng 好的，多谢！
