### ISSUE TITLE
这个库是不是还不能在Windows上使用啊

### ISSUE THREAD

**Issue by lujun495904500** [aliyun/aliyun-log-c-sdk#33]
看了下代码，VS应该是编译不过的。而且好像windows的部分不完整。有人在windows上使用过吗

**Comment by shabicheng** [comment]
使用live分支，https://github.com/aliyun/aliyun-log-c-sdk/tree/live/projects/windows

**Comment by lujun495904500** [comment]
哦，谢谢了， 这个默认进来是master，有点搞晕了
