### ISSUE TITLE
频繁的调用log_group_create及log_group_destroy

### ISSUE THREAD

**Issue by zhaowq32** [aliyun/aliyun-log-c-sdk#37]
单线程while(true)处理日志发送的情况下，能够提供一个清理已发送数据的接口，来避免频繁的malloc以及free

**Comment by shabicheng** [comment]
你是使用的producer嘛？producer内部会自动去处理内存相关，这个SDK对性能做了专门的优化，内存的申请释放次数很少

**Comment by zhaowq32** [comment]
log_group_builder* log_group_create()
{
    log_group_builder* bder = (log_group_builder*)malloc(sizeof(log_group_builder)+sizeof(log_group));
    memset(bder, 0, sizeof(log_group_builder)+sizeof(log_group));
    bder->grp = (log_group*)((char *)(bder) + sizeof(log_group_builder));
    bder->loggroup_size = sizeof(log_group) + sizeof(log_group_builder);
    bder->builder_time = time(NULL);
    return bder;
}

void log_group_destroy(log_group_builder* bder)
{
    // free tag
    log_group* group = bder->grp;
    if (group->tags.buffer != NULL)
    {
        free(group->tags.buffer);
    }
    // free log
    if (group->logs.buffer != NULL)
    {
        free(group->logs.buffer);
    }
    if (group->topic != NULL)
    {
        sdsfree(group->topic);
    }
    if (group->source != NULL)
    {
        sdsfree(group->source);
    }
    // free self
    free(bder);
}

**Comment by zhaowq32** [comment]
使用的bricks分支代码

**Comment by shabicheng** [comment]
嗯，明白你的意思，builder使用完毕后必须销毁，这里面的内存结构会比较复杂，如果实现清空的逻辑会让代码变的非常臃肿。

每个loggroup可以发送4096条日志，每次发送完后创建/销毁相对还是内存友好的，其他语言的SDK每次增加一条日志都会有N次的内存申请/释放（N=日志key数量*2），相比已经降低了1个数量级。

如果你们程序中malloc free很慢，可以使用tcmalloc来加速

**Comment by zhaowq32** [comment]
好的，多谢您的解答。
