### ISSUE TITLE
More details needed if curl, apr and apr-util are installed to a user-defined locations

### ISSUE THREAD

**Issue by yaojingguo** [aliyun/aliyun-log-c-sdk#46]
Since CMake use `curl-config`, `apr-1-1config`, and ` apu-1-config`, they needs to be available in PATH.  If curl, apr and apr-util are installed to user-defined locations, the directories containing them should be added to PATH.

**Comment by shabicheng** [comment]
#44 fixed this

**Comment by yaojingguo** [comment]
#44 does not fix this. https://github.com/aliyun/aliyun-log-c-sdk/pull/46 and https://github.com/aliyun/aliyun-log-c-sdk/pull/47 fix this.
