### ISSUE TITLE
使用live分支，vs2017编译测试代码，上传中文内容，后台显示乱码

### ISSUE THREAD

**Issue by Guo0625** [aliyun/aliyun-log-c-sdk#59]
使用live分支，vs2017编译测试代码，上传中文内容后台显示乱码。这个是什么原因呢？

**Comment by shabicheng** [comment]
确认你的中文是否是UTF-8编码，SLS控制台上中文编码都是UTF-8的

**Comment by Guo0625** [comment]
https://blog.csdn.net/Love_Point/article/details/105658241将visual studio中代码格式修改为utf-8编码格式，后台不再乱码。
