### ISSUE TITLE
transport failure curl code:45 error:Failed binding local connection end -996 HttpIoError Failed binding local connection end

### ISSUE THREAD

**Issue by billnie** [aliyun/aliyun-log-c-sdk#9]
transport failure curl code:45 error:Failed binding local connection end
-996
HttpIoError
Failed binding local connection end

**Comment by billnie** [comment]
aos_transport.c
comment the follow code done
    // interface
//    if (t->interface != NULL){
//        curl_easy_setopt_safe(CURLOPT_INTERFACE, t->interface);
//    }

**Comment by shabicheng** [comment]
you should set t->interface to NULL, not comment it
